# bin size and quality
bin_size: 10000
mapping_quality: 60
# blacklist used
blacklistFile: "resources/Blacklist_XY.bed"
# aligner params for bwa mem2
bwa_genome: "/Volumes/shared-refs/gatk_resources/hg38/v0/bwa-mem2-index/Homo_sapiens_assembly38.fasta"
# peak calling params for macs2
effective_genome_size: 2913022398
macs2_minimum_fdr: 0.05
# Modules
bwamem2: "bwa-mem2/2.0"
fastqc: "fastqc/0.12.1"
fastp: "fastp/0.23.2"
samtools: "samtools/1.18"
macs2: "macs2/2.2.7.1"
deeptools: "deeptools/3.4.3"
Bioconductor: "bioconductor/3.14"
bedtools: "bedtools/2.30.0"
